WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 424
VIRTUAL_HEIGHT = 216

TILE_SIZE = 16

PLAYER_WALK_SPEED = 60

BACKGROUND_SCROLL_SPEED = 25
BACKGROUND_LOOPING_POINT = 432

MAP_WIDTH = math.floor(VIRTUAL_WIDTH / TILE_SIZE) - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 1

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

BACKGROUNDS = {1, 2}

TILE_EMPTY = 8

TILE_SCONCE = 7

TILE_GLASS = 9

TILE_FLOOR = 1

TILE_TOP_WALL = 2
TILE_TOP_WALL_BOTTOM = 10

DELIMITER_TOP = 4

DELIMITER_BOTTOM = 3

DELIMITER_LEFT = 5

DELIMITER_RIGHT = 6

DELIMITER_TOP_LEFT_CORNER = 11

DELIMITER_TOP_RIGHT_CORNER = 12

DELIMITER_BOTTOM_LEFT_CORNER = 13

DELIMITER_BOTTOM_RIGHT_CORNER = 14