WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 424
VIRTUAL_HEIGHT = 216

TILE_SIZE = 16

PLAYER_WALK_SPEED = 60

BACKGROUND_SCROLL_SPEED = 25
BACKGROUND_LOOPING_POINT = 432

MAP_WIDTH = math.floor(VIRTUAL_WIDTH / TILE_SIZE) - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 1

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

BACKGROUNDS = {1, 2}

TILE_EMPTY = 13

TILE_GLASS = 4

TILE_FLOORS = {1}

TILE_TOP_WALLS = {2}
TILE_TOP_WALL_BOTTOM = 3

DELIMITER_TOP = 6

DELIMITER_BOTTOM = 5

DELIMITER_LEFT = 7

DELIMITER_RIGHT = 8

DELIMITER_TOP_LEFT_CORNER = 9

DELIMITER_TOP_RIGHT_CORNER = 10

DELIMITER_BOTTOM_LEFT_CORNER = 11

DELIMITER_BOTTOM_RIGHT_CORNER = 12